name: Install JIRA binary

on:
  workflow_dispatch:

jobs:
  install-docker:
    runs-on: self-hosted

    steps:
      - name: Installation of jira binary
        run: |
          cd ~
          wget https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-11.3.6-x64.exe
